### ISSUE TITLE
Error Event received... Error: Not a feed

### ISSUE THREAD

**Issue by pmoelgaard** [pmoelgaard/google-news#1]
After a while the API stops querying and it returns this error.
It's possible it's because the internet connection is broken or other problems related to the API's underlying queries returning something else than the expected feed.

**Comment by GirishGaikwad** [comment]
Hi Peter,
I checked multiple it is not because of the broken connection.
Possibly google is blocking the API's queries after some time.
Any Solution on this issue?

**Comment by bogstandard** [comment]
Not a solution but a workaround: Manually navigate to a Google News RSS feed in browser and complete the Captcha. This should bring the API back to normal until it decides to block you again.

Example URL to navigate to: [https://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&output=rss](https://news.google.com/news?pz=1&cf=all&ned=uk&hl=en&output=rss)
