### ISSUE TITLE
Passing date parameter to request

### ISSUE THREAD

**Issue by mdjasper** [pmoelgaard/google-news#2]
Is there any way to pass a date parameter into the news request? You can select a date range in the Google News web UI, and it is passed using in the `tbs` parameter:

 `https://www.google.com/search?q=google&hl=en&gl=us&authuser=0&source=lnt&tbs=cdr%3A1%2Ccd_min%3A9%2F1%2F2015%2Ccd_max%3A9%2F2%2F2015&tbm=nws`

![image](https://cloud.githubusercontent.com/assets/698211/10113305/199960d4-63a0-11e5-9220-9c37fcf91373.png)

I passed this parameter into the constructor, but it doesn't seem to be included in the request:

```
googleNews = new GoogleNews({
    params:{
        tbs: 'cdr:1,cd_min:9/1/2010,cd_max:9/1/2010'
    }
}),
```

Do you have any tips or examples on how to include a date range into the request?

**Comment by pmoelgaard** [comment]
Hi Jasper, let me take a look at why it doesn't work...
Thanks for the heads up !

**Comment by pmoelgaard** [comment]
Actually, I cant from the Google News Site find any results, and I have tried to search historically on news for e.g. Facebook in January this year, which yields empty results. I think we have to conclude that historically searching wont work.

**Comment by mdjasper** [comment]
Historic search does work from the web UI. Try this url:

https://www.google.com/search?q=facebook&safe=strict&hl=en&gl=us&authuser=0&source=lnt&tbs=cdr%3A1%2Ccd_min%3A1%2F1%2F2015%2Ccd_max%3A1%2F31%2F2015&tbm=nws

![image](https://cloud.githubusercontent.com/assets/698211/10123303/afeba476-64f3-11e5-8de2-4c263aeda20a.png)

**Comment by pmoelgaard** [comment]
Yes, now I can get the history to work too.

**Comment by julox** [comment]
it's strange, the history doesn't work in others app for example Curl or Rvest, I don't undersant

**Comment by LRonHubs** [comment]
Anyone able to figure this out?
